# Central definition of the required LiteX packages and their pinned
# versions.

[litex]
github_user = "enjoy-digital"
github_repo = "litex"

# litex master of Jul 15, 2021, 7:00 PM GMT+2
git_revision = "e0d5a7bff55923"

github_archive_nix_hash = "sha256-wPhrnPdRDhNbU2qRUz9I2zkcDc92JnPQZfPDdpCEcyU="

[litex-boards]
github_user = "litex-hub"
github_repo = "litex-boards"

# litex-boards master of Jul 16, 2021, 2:41 PM GMT+2
git_revision = "4b48f15265c902"

github_archive_nix_hash = "sha256-SJ/xhAfdQDerwIUl1aLt+I3BdkNHHIZ6bjTug/0Mu3g="

[liteeth]
github_user = "enjoy-digital"
github_repo = "liteeth"

# liteeth master of Jul 16, 2021, 5:50 PM GMT+2
git_revision = "947ed037202a99"

github_archive_nix_hash = "sha256-muPIG+7d57OTLJ4i0JlADLmo18qFfQONjRCUVHUPvUE="

[litedram]
github_user = "enjoy-digital"
github_repo = "litedram"

# litedram master of Jul 13, 2021, 2:57 PM GMT+2
git_revision = "4326fe7f36699a"

github_archive_nix_hash = "sha256-CUj5vQAT0eB1qT5+6kz5x/3/hty/UgqKwizoIx8BC6g="

[litehyperbus]
github_user = "litex-hub"
github_repo = "litehyperbus"

# litehyperbus master of Jun 14, 2021, 8:03 AM GMT+2
git_revision = "b7d57e9c63b1f2"

github_archive_nix_hash = "sha256-Xe3octAF+E124J5+1EQnSObuKqybu8SU/Ig38hWRcgE="

[liteiclink]
github_user = "enjoy-digital"
github_repo = "liteiclink"

# liteiclink master of Apr 1, 2021, 6:59 PM GMT+2
git_revision = "3d8ecdbcf9f026"

github_archive_nix_hash = "0blvgg26pf174nl8gi91a3aahalav0l4fcqdyphhc2i49iz63rnr"

[litepcie]
github_user = "enjoy-digital"
github_repo = "litepcie"

# litepcie master of Jul 2, 2021, 3:46 PM GMT+2
git_revision = "68334fd93d078c"

github_archive_nix_hash = "sha256-/XY3HoC3aJCsUZkRNJSZVE1UwrMHoear7CycAELtMtE="

[litescope]
github_user = "enjoy-digital"
github_repo = "litescope"

# litescope master of May 3, 2021, 12:12 PM GMT+2
git_revision = "72c9930705ccc5"

github_archive_nix_hash = "sha256-s0JrgAoxYgNOE9SEOWV869yqAeBEfiXSslKKhul8qhY="

[litespi]
github_user = "litex-hub"
github_repo = "litespi"

# litespi master of Jun 27, 2021, 9:21 PM GMT+2
git_revision = "51eabb52248ab5"

github_archive_nix_hash = "sha256-FxFsFx57d5PpymDf3c4ZArESiUMlSKFz/uImcpbcoQU="

[migen]
github_user = "m-labs"
github_repo = "migen"

git_revision = "0.9.2"

github_archive_nix_hash = "1kq11if64zj84gv4w1q7l16fp17xjxl2wv5hc9dibr1z3m1gy67l"


[pythondata-cpu-vexriscv]
# For now, this entry is not used by Nix and needs to be kept in sync
# manually. This is not a simple repository and hash, but a release
# tarball which needs to be installed.

version = "2021030800"
tarball_url = "https://github.com/lschuermann/litex-vexriscv-custom/releases/download/2021030800/generated.tar.gz"

[pythondata-misc-tapcfg]
github_user = "litex-hub"
github_repo = "pythondata-misc-tapcfg"

# pythondata-misc-tapcfg master of Mar 5, 2021, 9:48 PM GMT+1
git_revision = "0e6809132b7a42"

github_archive_nix_hash = "182m452iclahx1ipic0x7q4c9w33w6vfm9lz8zbx39zli9dg7l03"

[pythondata-software-compiler_rt]
github_user = "litex-hub"
github_repo = "pythondata-software-compiler_rt"

git_revision = "2020.08"

github_archive_nix_hash = "0b65dj95418j4pjqqkqjq5npnn1ih1789ba9575kxcljgj7r8xb7"