name: tock-litex-ci
on:
  pull_request:
  push:
jobs:
  ci-release-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4

    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Perform a release build with proprietary toolchain steps disabled
      run: nix-build --arg enableVivado false release.nix

    - name: Upload built results
      uses: actions/upload-artifact@v2
      with:
        name: release-build-novivado
        # Glob required here, see https://github.com/actions/upload-artifact/issues/92
        path: 'result*/*'
